name: Release Plugin

on:
  push:
    tags:
      - 'v*' # Trigger on any tag that starts with "v"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get all commits for tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # Or your go version

      - name: Compile Plugin WASM
        run: GOOS=wasip1 GOARCH=wasm go build -ldflags="-s -w" -o main.wasm main.go

      - name: Calculate SHA256 Checksum
        id: checksum
        run: echo "sha256=$(sha256sum main.wasm | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Set Release Tag
        id: vars
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.TAG_NAME }}
          files: main.wasm
          body: |
            This release includes the sqlc-gen-r plugin WASM.

            To use this plugin, configure your `sqlc.yaml` as follows:

            ```yaml
            version: "2"
            plugins:
            - name: sqlc-gen-r
              wasm:
                url: https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.TAG_NAME }}/main.wasm
                sha256: ${{ steps.checksum.outputs.sha256 }}
            sql:
              - engine: "sqlite"
                queries: "queries.sql"
                schema: "schema.sql"
                codegen:
                - out: out
                  plugin: sqlc-gen-r
                  options:
                    filename: "db.R"
            ```

